# Używamy oficjalnego, lekkiego obrazu Pythona
FROM python:3.12-slim

# Ustawiamy katalog roboczy wewnątrz kontenera
WORKDIR /app

# Kopiujemy plik z bibliotekami i instalujemy je
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiujemy całą resztę Twojego kodu
COPY . .

# Wystawiamy port 8000
EXPOSE 8000

# Komenda, która odpali FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]